title CONTAR QUANTOS 'A' EM UM VETOR DE 20 ELEMENTOS
.MODEL SMALL
.DATA
    VETOR DB 20 DUP(0)
    MSG1 DB 10,13,"Digite o nome: $"
    MSG2 DB 10,13,"Digite uma letra (maiúscula): $"
    MSG3 DB 10,13,"Número de instâncias: $"

.STACK 100H
.CODE
MAIN PROC
    MOV AX, @DATA
    MOV DS, AX

    MOV AH, 9
    LEA DX, MSG1
    INT 21H

    LEA SI, VETOR
    MOV CX, 20
    CALL LEITURA        ;RECEBE UM NOME DE ATÉ 20 CARACTERES E O COLOCA EM VETOR

    MOV AH, 9
    LEA DX, MSG2
    INT 21H
    MOV CX, 20
    CALL SEARCH

    MOV AH, 9
    LEA DX, MSG3
    CALL PRINT

    MOV AH, 4CH
    INT 21H
MAIN ENDP

;RECEBE CARACTERES ATÉ PREENCHER OS 20 ELEMENTOS DO VETOR, OU ATÉ RECEBER O CR
;O ENDEREÇO DE VETOR DEVE ESTAR NO REGISTRADOR SI
;CX DEVE CONTER O NÚMERO DE ELEMENTOS NO VETOR
;O REGISTRADOR DI RETORNARÁ A POSIÇÃO DE MEMÓRIA DO ÚLTIMO CARACTERE 
LEITURA PROC
    MOV AH, 1
    MOV DI, SI
    INPUT:
        INT 21H             ;LER CARACTERE
        CMP AL, 13
        JZ SAIR             ;SE INPUT = CR, SAIR DO LOOP
        MOV [DI], AL        ;CASO CONTRÁRIO, ARMAZENAR NO VETOR NA POSÍÇÃO DI
        INC DI              ;AVANÇA DI PARA O PRÓXIMO ELEMENTO
        LOOP INPUT          ;SE O LOOP RODOU 20 VEZER (NÚMERO CONTIDO EM CX ANTES DE ENTRAR NO LOOP), SAIR

    SAIR:
    RET

LEITURA ENDP

;REALIZA A BUSCA POR UMA LETRA ESPECÍFICA EM UM VETOR DE 20 ELEMENTOS, RETORNA O NÚMERO DE VEZES QUE ESSA LETRA APARECE
;ESSA LETRA SERÁ ARMAZENADA NO REGISTRADOR AL
;O ENDEREÇO DO VETOR DEVE ESTAR EM SI
;CX DEVE CONTER TAMANHO DO VETOR
SEARCH PROC
    MOV AH, 1
    INT 21H                 ;RECEBE A LETRA A SER PROCURADA (GUARDADA EM AL)
    XOR BH, BH              ;BH SERÁ UTILIZADO COMO CONTADOR PARA O NÚMERO DE LETRAS ENCONTRADAS
    MOV DI, SI
    PROCURA:
        MOV BL, [DI]        ;BL SERÁ UTILIZADO PARA CONTER A LETRA SENDO COMPARADA
        CMP BL, AL          ;COMPARA LETRA NO VETOR COM A LETRA PROCURADA
        JNZ SEGUE           ;SE NÃO CORRESPONDER A LETRA PROCURADA, PULAR
        INC BH              ;SE CORRESPONDER, BH++

        SEGUE:
        INC DI              ;DI AVANÇA PARA O PRÓXIMO ELEMENTO DO VETOR
        LOOP PROCURA        ;LOOP RODA ATÉ LER O ÚLTIMO ELEMENTO DO VETOR (QUANDO CX = 0)
    RET
SEARCH ENDP

;IMPRIME O NÚMERO DE VEZES QUE A LETRA APARECE
;NUMERO DE INSTANCIAS DEVE ESTAR EM BH
PRINT PROC
    MOV AH, 2
    MOV DL, BH              ;PASSA CONTADOR DE BH PARA DL
    OR DL, 30H              ;CONVERTE DE NÚMERO PARA CARACTERE NUMÉRICO
    INT 21H                 ;IMPRIME

    RET
PRINT ENDP
END MAIN