title RECEBE UM NOME DE ATÉ 20 CARACTERES E IMPRIME AS INICIAIS DESSE NOME
.MODEL SMALL
.DATA
    NOME DB 20 DUP(0)
.STACK 100H
.CODE
MAIN PROC
    MOV AX, @DATA
    MOV DS, AX

    CALL RECEBERNOME
    CALL INICIAIS

    MOV AH, 4CH
    INT 21H
MAIN ENDP

;RECEBE UM NOME DE ATÉ 20 CARACTERES E O ARMAZENA NA MEMÓRIA
RECEBERNOME PROC
    PUSH AX
    PUSH CX
    PUSH SI

    XOR SI, SI
    MOV CX, 20
    MOV AH, 1
    INPUT:
        INT 21H
        CMP AL, 13                  ;SE INPUT FOR O CR, SAIR DO LOOP
        JZ SAIR
        MOV BYTE PTR [SI], AL       ;COLOCA O CARACTERE DIGITADO NO VETOR
        INC SI
        LOOP INPUT
    SAIR:
    POP SI
    POP CX
    POP AX
    RET
RECEBERNOME ENDP

;LÊ O VETOR E IMPRIME AS INICIAIS DO NOME
INICIAIS PROC
    PUSH AX
    PUSH DX
    PUSH SI

    XOR SI, SI
    MOV CX, 20
    MOV AH, 2
    MOV DL, NOME[SI]
    INT 21H                             ;IMPRIME A PRIMEIRA LETRA DO NOME
    PRINT:
        MOV AL, NOME[SI]
        CMP AL, 20h                     ;SE O CARACTERE NÃO FOR UM ESPAÇO, PULAR
        JNZ ESPAÇO
        MOV DL, NOME[SI+1]              ;IMPRIME A LETRA LOGO APÓS O EXPAÇO
        INT 21H
        ESPAÇO:
        INC SI
        LOOP PRINT

    POP SI
    POP DX
    POP AX
    RET
INICIAIS ENDP
END MAIN