title LEITURA DIAGONAL DE UMA MATRIZ 4X4
.MODEL SMALL
.DATA
    MATRIZ DB    1,  2,  3,  4
           DB    5,  6,  7,  8
           DB    9, 10, 11, 12
           DB   13, 14, 15, 16
    
.CODE
MAIN PROC
    MOV AX, @DATA
    MOV DS, AX

    MOV AX, 0
    MOV BX, 0
    MOV CX, 0
    MOV DX, 0

    CALL DIAGONAL
    CALL SAIDADECIMAL
    
    MOV AH, 4CH
    INT 21H
MAIN ENDP

;LE A DIAGONAL PRINCIPAL DE UMA MATRIX 4X4 E COLOCA ESSE NÚMERO EM DX
DIAGONAL PROC
    PUSH SI
    PUSH DX
    PUSH CX

    XOR SI, SI
    XOR BX, BX
    MOV CX, 4
    XOR DX, DX
    SOMA:
        ADD DL, MATRIZ[BX][SI]
        INC SI
        ADD BX, 4
        LOOP SOMA

    MOV BX, DX
    POP CX
    POP DX
    POP SI
    RET
DIAGONAL ENDP

;IMPRIME NÚMERO DECIMAL ARMAZENADO EM BX
;PODE IMPRIMIR NÚMEROS DE 1 ATÉ 262143
SAIDADECIMAL PROC
    PUSH AX
    PUSH BX
    PUSH CX
    PUSH DX

    MOV DI, 10
    XOR CX, CX
    MOV AX, BX          ;PASSA O NUMERO A SER DIVIDIDO PARA AX
    
    OUTPUTDECIMAL:
        DIV DI              ;AX / DI    --> QUOCIENTE VAI PARA AX E RESTO VAI PARA DX
        PUSH DX
        XOR DX, DX
        INC CX
        OR AX, AX
        JNZ OUTPUTDECIMAL
    
    MOV AH, 2
    IMPRIMIRDECIMAL:
        POP DX
        OR DL, 30H
        INT 21H
        LOOP IMPRIMIRDECIMAL

    POP DX
    POP CX
    POP BX
    POP AX
    RET
SAIDADECIMAL ENDP
END MAIN